import { GameModeType } from './GameMode';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type SurfaceType =
  | 'sphere'
  | 'cube'
  | 'pill'
  | 'pipe'
  | 'torus'
  | 'peanut'
  | 'capsule'
  | 'icosahedron'
  | 'mobius'
  | 'sphere-tunnel'
  | 'cube-ring';

export interface WaveDefinition {
  /** Delay in seconds before this wave spawns. */
  delay: number;
  /** Enemy types and counts for this wave. */
  enemies: Array<{ type: string; count: number }>;
}

export interface LevelDefinition {
  id: number;
  name: string;
  section: string;
  mode: GameModeType;
  surface: SurfaceType;
  /** Surface radius/size. */
  surfaceScale: number;
  /** Time limit in seconds (0 = no limit). */
  timeLimit: number;
  lives: number;
  bombs: number;
  supers: number;
  starThresholds: [number, number, number];
  waves: WaveDefinition[];
}

// ---------------------------------------------------------------------------
// Adventure Mode Levels
// ---------------------------------------------------------------------------

export const ADVENTURE_LEVELS: LevelDefinition[] = [
  // ---- Sapphire Section (1-5) ----
  {
    id: 1,
    name: 'The Beginning',
    section: 'Sapphire',
    mode: GameModeType.Deadline,
    surface: 'sphere',
    surfaceScale: 8,
    timeLimit: 90,
    lives: 0,
    bombs: 0,
    supers: 1,
    starThresholds: [100_000, 200_000, 500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'wanderer', count: 8 }] },
      { delay: 5, enemies: [{ type: 'wanderer', count: 6 }, { type: 'duck', count: 4 }] },
      { delay: 12, enemies: [{ type: 'grunt', count: 6 }] },
      { delay: 20, enemies: [{ type: 'wanderer', count: 10 }, { type: 'grunt', count: 4 }] },
      { delay: 30, enemies: [{ type: 'grunt', count: 10 }, { type: 'mayfly', count: 15 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 15 }, { type: 'wanderer', count: 8 }] },
      { delay: 60, enemies: [{ type: 'grunt', count: 20 }, { type: 'mayfly', count: 20 }] },
    ],
  },
  {
    id: 2,
    name: 'Dead Planet',
    section: 'Sapphire',
    mode: GameModeType.Deadline,
    surface: 'sphere',
    surfaceScale: 10,
    timeLimit: 120,
    lives: 0,
    bombs: 0,
    supers: 1,
    starThresholds: [700_000, 1_200_000, 2_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 10 }] },
      { delay: 8, enemies: [{ type: 'grunt', count: 8 }, { type: 'wanderer', count: 6 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 12 }, { type: 'rocket', count: 4 }] },
      { delay: 30, enemies: [{ type: 'mayfly', count: 25 }, { type: 'grunt', count: 8 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 15 }, { type: 'rocket', count: 6 }, { type: 'wanderer', count: 8 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 20 }, { type: 'mayfly', count: 30 }] },
      { delay: 85, enemies: [{ type: 'grunt', count: 25 }, { type: 'rocket', count: 8 }, { type: 'weaver', count: 4 }] },
    ],
  },
  {
    id: 3,
    name: 'Twisted Blister',
    section: 'Sapphire',
    mode: GameModeType.Evolved,
    surface: 'peanut',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 3,
    bombs: 0,
    supers: 1,
    starThresholds: [500_000, 5_000_000, 15_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 8 }] },
      { delay: 10, enemies: [{ type: 'grunt', count: 10 }, { type: 'wanderer', count: 6 }] },
      { delay: 25, enemies: [{ type: 'grunt', count: 12 }, { type: 'weaver', count: 4 }] },
      { delay: 40, enemies: [{ type: 'spinner', count: 6 }, { type: 'grunt', count: 10 }] },
      { delay: 60, enemies: [{ type: 'grunt', count: 15 }, { type: 'spinner', count: 8 }, { type: 'mayfly', count: 20 }] },
    ],
  },
  {
    id: 4,
    name: 'Soul Window',
    section: 'Sapphire',
    mode: GameModeType.Deadline,
    surface: 'cube',
    surfaceScale: 12,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 4_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 12 }] },
      { delay: 10, enemies: [{ type: 'grunt', count: 10 }, { type: 'weaver', count: 4 }] },
      { delay: 25, enemies: [{ type: 'spinner', count: 6 }, { type: 'grunt', count: 8 }, { type: 'rocket', count: 4 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 15 }, { type: 'weaver', count: 6 }, { type: 'mayfly', count: 20 }] },
      { delay: 60, enemies: [{ type: 'grunt', count: 20 }, { type: 'spinner', count: 8 }, { type: 'rocket', count: 6 }] },
      { delay: 80, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }, { type: 'spinner', count: 6 }] },
    ],
  },
  {
    id: 5,
    name: 'Sapphire',
    section: 'Sapphire',
    mode: GameModeType.Boss,
    surface: 'sphere',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 3_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'boss_sapphire', count: 1 }] },
    ],
  },

  // ---- Ruby Section (6-10) ----
  {
    id: 6,
    name: 'Sausage Smash',
    section: 'Ruby',
    mode: GameModeType.Deadline,
    surface: 'capsule',
    surfaceScale: 8,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 4_000_000, 5_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }] },
      { delay: 10, enemies: [{ type: 'grunt', count: 12 }, { type: 'spinner', count: 4 }] },
      { delay: 25, enemies: [{ type: 'weaver', count: 6 }, { type: 'grunt', count: 10 }, { type: 'rocket', count: 6 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 20 }, { type: 'spinner', count: 8 }, { type: 'mayfly', count: 25 }] },
      { delay: 60, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }, { type: 'rocket', count: 8 }] },
      { delay: 80, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }] },
    ],
  },
  {
    id: 7,
    name: 'Maze',
    section: 'Ruby',
    mode: GameModeType.Checkpoint,
    surface: 'pill',
    surfaceScale: 8,
    timeLimit: 60,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [500_000, 1_750_000, 3_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 10 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 12 }, { type: 'wanderer', count: 6 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }, { type: 'rocket', count: 4 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 18 }, { type: 'weaver', count: 4 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'spinner', count: 6 }] },
    ],
  },
  {
    id: 8,
    name: 'Titan World',
    section: 'Ruby',
    mode: GameModeType.Titan,
    surface: 'sphere',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [250_000, 2_000_000, 6_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'titan_grunt', count: 3 }] },
      { delay: 15, enemies: [{ type: 'titan_grunt', count: 4 }, { type: 'titan_spinner', count: 2 }] },
      { delay: 35, enemies: [{ type: 'titan_grunt', count: 5 }, { type: 'titan_spinner', count: 3 }] },
    ],
  },
  {
    id: 9,
    name: 'Sweep',
    section: 'Ruby',
    mode: GameModeType.Deadline,
    surface: 'torus',
    surfaceScale: 8,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [1_500_000, 2_500_000, 3_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 12 }, { type: 'wanderer', count: 8 }] },
      { delay: 12, enemies: [{ type: 'grunt', count: 15 }, { type: 'rocket', count: 6 }] },
      { delay: 28, enemies: [{ type: 'grunt', count: 18 }, { type: 'weaver', count: 6 }, { type: 'neutron', count: 4 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 22 }, { type: 'spinner', count: 6 }, { type: 'rocket', count: 8 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 28 }, { type: 'weaver', count: 8 }, { type: 'neutron', count: 6 }] },
    ],
  },
  {
    id: 10,
    name: 'Ruby',
    section: 'Ruby',
    mode: GameModeType.Boss,
    surface: 'capsule',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 1_500_000, 3_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'boss_ruby', count: 1 }] },
    ],
  },

  // ---- Emerald Section (11-20) ----
  {
    id: 11,
    name: 'Peanut Dreams',
    section: 'Emerald',
    mode: GameModeType.Deadline,
    surface: 'peanut',
    surfaceScale: 10,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 2,
    starThresholds: [4_000_000, 7_000_000, 10_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }, { type: 'weaver', count: 4 }] },
      { delay: 12, enemies: [{ type: 'grunt', count: 18 }, { type: 'spinner', count: 6 }] },
      { delay: 28, enemies: [{ type: 'grunt', count: 22 }, { type: 'rocket', count: 8 }, { type: 'weaver', count: 6 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }, { type: 'mayfly', count: 30 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 30 }, { type: 'weaver', count: 10 }, { type: 'spinner', count: 8 }] },
      { delay: 85, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 10 }, { type: 'rocket', count: 10 }] },
    ],
  },
  {
    id: 12,
    name: 'Gate Dash',
    section: 'Emerald',
    mode: GameModeType.Pacifism,
    surface: 'sphere',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 1,
    bombs: 0,
    supers: 0,
    starThresholds: [750_000, 1_800_000, 3_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'gate', count: 6 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 15 }, { type: 'gate', count: 4 }] },
      { delay: 30, enemies: [{ type: 'grunt', count: 20 }, { type: 'gate', count: 5 }] },
    ],
  },
  {
    id: 13,
    name: 'King Hot Dog',
    section: 'Emerald',
    mode: GameModeType.King,
    surface: 'capsule',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 1,
    bombs: 0,
    supers: 1,
    starThresholds: [50_000, 150_000, 500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 10 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 12 }, { type: 'wanderer', count: 6 }] },
      { delay: 30, enemies: [{ type: 'grunt', count: 15 }, { type: 'spinner', count: 4 }] },
    ],
  },
  {
    id: 14,
    name: 'Cubism',
    section: 'Emerald',
    mode: GameModeType.Rainbow,
    surface: 'cube',
    surfaceScale: 12,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [500_000, 1_000_000, 3_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'painter', count: 5 }, { type: 'grunt', count: 8 }] },
      { delay: 20, enemies: [{ type: 'painter', count: 6 }, { type: 'grunt', count: 10 }] },
    ],
  },
  {
    id: 15,
    name: 'Equator',
    section: 'Emerald',
    mode: GameModeType.Deadline,
    surface: 'sphere',
    surfaceScale: 12,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 1_700_000, 2_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }, { type: 'rocket', count: 6 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 18 }, { type: 'neutron', count: 6 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 22 }, { type: 'weaver', count: 6 }, { type: 'rocket', count: 8 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
      { delay: 75, enemies: [{ type: 'grunt', count: 30 }, { type: 'weaver', count: 8 }, { type: 'neutron', count: 8 }] },
    ],
  },
  {
    id: 16,
    name: 'Pianola Roller',
    section: 'Emerald',
    mode: GameModeType.Evolved,
    surface: 'pill',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [250_000, 1_750_000, 5_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 12 }] },
      { delay: 12, enemies: [{ type: 'grunt', count: 15 }, { type: 'rocket', count: 6 }] },
      { delay: 28, enemies: [{ type: 'grunt', count: 18 }, { type: 'spinner', count: 4 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 22 }, { type: 'weaver', count: 6 }] },
    ],
  },
  {
    id: 17,
    name: 'Rock',
    section: 'Emerald',
    mode: GameModeType.Evolved,
    surface: 'sphere',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 5_000_000, 15_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }, { type: 'weaver', count: 4 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 18 }, { type: 'spinner', count: 6 }, { type: 'rocket', count: 4 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 22 }, { type: 'weaver', count: 6 }, { type: 'neutron', count: 4 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 28 }, { type: 'spinner', count: 8 }, { type: 'mayfly', count: 25 }] },
      { delay: 80, enemies: [{ type: 'grunt', count: 35 }, { type: 'weaver', count: 10 }, { type: 'spinner', count: 8 }] },
    ],
  },
  {
    id: 18,
    name: 'Spawn',
    section: 'Emerald',
    mode: GameModeType.Evolved,
    surface: 'sphere',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [500_000, 2_500_000, 7_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'spawner', count: 2 }, { type: 'grunt', count: 8 }] },
      { delay: 20, enemies: [{ type: 'spawner', count: 3 }, { type: 'grunt', count: 10 }] },
      { delay: 45, enemies: [{ type: 'spawner', count: 4 }, { type: 'weaver', count: 4 }] },
    ],
  },
  {
    id: 19,
    name: 'Infected',
    section: 'Emerald',
    mode: GameModeType.Evolved,
    surface: 'peanut',
    surfaceScale: 8,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [250_000, 1_000_000, 3_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'virus', count: 3 }, { type: 'grunt', count: 8 }] },
      { delay: 20, enemies: [{ type: 'virus', count: 4 }, { type: 'grunt', count: 10 }] },
    ],
  },
  {
    id: 20,
    name: 'Emerald',
    section: 'Emerald',
    mode: GameModeType.Boss,
    surface: 'sphere',
    surfaceScale: 12,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 4_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'boss_emerald', count: 1 }] },
    ],
  },

  // ---- Opal Section (21-30) ----
  {
    id: 21,
    name: 'King Pond',
    section: 'Opal',
    mode: GameModeType.King,
    surface: 'torus',
    surfaceScale: 9,
    timeLimit: 0,
    lives: 1,
    bombs: 0,
    supers: 1,
    starThresholds: [250_000, 1_000_000, 2_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }, { type: 'wanderer', count: 8 }] },
      { delay: 12, enemies: [{ type: 'grunt', count: 18 }, { type: 'spinner', count: 6 }] },
      { delay: 28, enemies: [{ type: 'grunt', count: 22 }, { type: 'weaver', count: 6 }, { type: 'rocket', count: 4 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
    ],
  },
  {
    id: 22,
    name: 'Hexawave',
    section: 'Opal',
    mode: GameModeType.Sniper,
    surface: 'cube',
    surfaceScale: 14,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [50_000, 100_000, 200_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 10 }] },
      { delay: 8, enemies: [{ type: 'grunt', count: 12 }, { type: 'spinner', count: 4 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 15 }, { type: 'weaver', count: 4 }] },
      { delay: 30, enemies: [{ type: 'grunt', count: 18 }, { type: 'spinner', count: 6 }] },
    ],
  },
  {
    id: 23,
    name: 'Out of Time',
    section: 'Opal',
    mode: GameModeType.Checkpoint,
    surface: 'pill',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 5_000_000, 12_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'weaver', count: 6 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 30 }, { type: 'rocket', count: 8 }, { type: 'weaver', count: 6 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 10 }, { type: 'neutron', count: 6 }] },
    ],
  },
  {
    id: 24,
    name: 'Nufo Flow',
    section: 'Opal',
    mode: GameModeType.Pacifism,
    surface: 'sphere',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 0,
    supers: 1,
    starThresholds: [400_000, 2_000_000, 10_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'gate', count: 8 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 20 }, { type: 'gate', count: 6 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 25 }, { type: 'gate', count: 8 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 30 }, { type: 'gate', count: 10 }] },
    ],
  },
  {
    id: 25,
    name: 'Intensity',
    section: 'Opal',
    mode: GameModeType.Evolved,
    surface: 'peanut',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [2_500_000, 5_000_000, 15_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'weaver', count: 6 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }, { type: 'rocket', count: 6 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 30 }, { type: 'weaver', count: 8 }, { type: 'neutron', count: 6 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 10 }, { type: 'snake', count: 2 }] },
      { delay: 80, enemies: [{ type: 'grunt', count: 40 }, { type: 'weaver', count: 12 }, { type: 'repulsor', count: 3 }] },
    ],
  },
  {
    id: 26,
    name: 'The Scream',
    section: 'Opal',
    mode: GameModeType.Claustrophobia,
    surface: 'cube',
    surfaceScale: 12,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_500_000, 8_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 18 }, { type: 'weaver', count: 6 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 22 }, { type: 'spinner', count: 6 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 28 }, { type: 'rocket', count: 8 }, { type: 'weaver', count: 6 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 32 }, { type: 'spinner', count: 10 }, { type: 'neutron', count: 6 }] },
    ],
  },
  {
    id: 27,
    name: 'Abstract',
    section: 'Opal',
    mode: GameModeType.Rainbow,
    surface: 'sphere',
    surfaceScale: 9,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_500_000, 3_000_000, 6_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'painter', count: 8 }, { type: 'grunt', count: 12 }] },
      { delay: 25, enemies: [{ type: 'painter', count: 10 }, { type: 'grunt', count: 15 }, { type: 'weaver', count: 4 }] },
      { delay: 50, enemies: [{ type: 'painter', count: 12 }, { type: 'grunt', count: 18 }, { type: 'spinner', count: 6 }] },
    ],
  },
  {
    id: 28,
    name: 'Barrel Roll',
    section: 'Opal',
    mode: GameModeType.Deadline,
    surface: 'pill',
    surfaceScale: 10,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 4_000_000, 6_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'weaver', count: 6 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 30 }, { type: 'rocket', count: 10 }, { type: 'weaver', count: 8 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 12 }, { type: 'neutron', count: 8 }] },
      { delay: 75, enemies: [{ type: 'grunt', count: 40 }, { type: 'weaver', count: 12 }, { type: 'rocket', count: 12 }] },
      { delay: 95, enemies: [{ type: 'grunt', count: 45 }, { type: 'spinner', count: 15 }, { type: 'mayfly', count: 35 }] },
    ],
  },
  {
    id: 29,
    name: 'Planet of Peace',
    section: 'Opal',
    mode: GameModeType.Pacifism,
    surface: 'torus',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 0,
    supers: 0,
    starThresholds: [500_000, 3_000_000, 10_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 30 }, { type: 'gate', count: 10 }] },
      { delay: 20, enemies: [{ type: 'grunt', count: 25 }, { type: 'gate', count: 8 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 35 }, { type: 'gate', count: 12 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 40 }, { type: 'gate', count: 15 }] },
    ],
  },
  {
    id: 30,
    name: 'Opal',
    section: 'Opal',
    mode: GameModeType.Boss,
    surface: 'sphere',
    surfaceScale: 12,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 1_400_000, 2_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'boss_opal', count: 1 }] },
    ],
  },

  // ---- Amethyst Section (31-40) ----
  {
    id: 31,
    name: 'Repulsive',
    section: 'Amethyst',
    mode: GameModeType.Evolved,
    surface: 'capsule',
    surfaceScale: 9,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [500_000, 2_000_000, 5_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'repulsor', count: 4 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 25 }, { type: 'repulsor', count: 5 }, { type: 'weaver', count: 6 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 30 }, { type: 'repulsor', count: 6 }, { type: 'spinner', count: 8 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 35 }, { type: 'repulsor', count: 7 }, { type: 'snake', count: 2 }] },
    ],
  },
  {
    id: 32,
    name: 'Titans Revenge',
    section: 'Amethyst',
    mode: GameModeType.Titan,
    surface: 'sphere',
    surfaceScale: 12,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [500_000, 1_500_000, 5_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'titan_grunt', count: 5 }] },
      { delay: 20, enemies: [{ type: 'titan_grunt', count: 6 }, { type: 'titan_spinner', count: 3 }] },
      { delay: 45, enemies: [{ type: 'titan_grunt', count: 7 }, { type: 'titan_spinner', count: 4 }, { type: 'titan_weaver', count: 2 }] },
      { delay: 75, enemies: [{ type: 'titan_grunt', count: 8 }, { type: 'titan_spinner', count: 5 }, { type: 'titan_weaver', count: 3 }] },
    ],
  },
  {
    id: 33,
    name: 'Dome of Doom',
    section: 'Amethyst',
    mode: GameModeType.Deadline,
    surface: 'sphere',
    surfaceScale: 13,
    timeLimit: 150,
    lives: 0,
    bombs: 2,
    supers: 2,
    starThresholds: [6_000_000, 10_000_000, 20_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }, { type: 'rocket', count: 8 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 35 }, { type: 'weaver', count: 12 }, { type: 'neutron', count: 8 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 15 }, { type: 'snake', count: 3 }] },
      { delay: 90, enemies: [{ type: 'grunt', count: 45 }, { type: 'weaver', count: 15 }, { type: 'repulsor', count: 6 }] },
      { delay: 115, enemies: [{ type: 'grunt', count: 50 }, { type: 'spinner', count: 18 }, { type: 'rocket', count: 15 }] },
    ],
  },
  {
    id: 34,
    name: 'Infected Planet',
    section: 'Amethyst',
    mode: GameModeType.Evolved,
    surface: 'peanut',
    surfaceScale: 11,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 4_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'virus', count: 5 }, { type: 'grunt', count: 15 }] },
      { delay: 25, enemies: [{ type: 'virus', count: 6 }, { type: 'grunt', count: 20 }, { type: 'weaver', count: 6 }] },
      { delay: 55, enemies: [{ type: 'virus', count: 7 }, { type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
    ],
  },
  {
    id: 35,
    name: 'Endurance',
    section: 'Amethyst',
    mode: GameModeType.Deadline,
    surface: 'torus',
    surfaceScale: 12,
    timeLimit: 180,
    lives: 0,
    bombs: 3,
    supers: 3,
    starThresholds: [75_000_000, 125_000_000, 200_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 30 }, { type: 'weaver', count: 10 }] },
      { delay: 20, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 12 }, { type: 'rocket', count: 10 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 40 }, { type: 'weaver', count: 15 }, { type: 'neutron', count: 10 }] },
      { delay: 70, enemies: [{ type: 'grunt', count: 45 }, { type: 'spinner', count: 18 }, { type: 'snake', count: 4 }] },
      { delay: 95, enemies: [{ type: 'grunt', count: 50 }, { type: 'weaver', count: 18 }, { type: 'repulsor', count: 8 }] },
      { delay: 120, enemies: [{ type: 'grunt', count: 55 }, { type: 'spinner', count: 20 }, { type: 'rocket', count: 18 }] },
      { delay: 145, enemies: [{ type: 'grunt', count: 60 }, { type: 'weaver', count: 22 }, { type: 'gravity_well', count: 3 }] },
    ],
  },
  {
    id: 36,
    name: 'Trash Compactor',
    section: 'Amethyst',
    mode: GameModeType.Claustrophobia,
    surface: 'cube',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 4_000_000, 6_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 22 }, { type: 'weaver', count: 8 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 28 }, { type: 'spinner', count: 8 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 35 }, { type: 'rocket', count: 10 }, { type: 'weaver', count: 8 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 12 }, { type: 'neutron', count: 8 }] },
    ],
  },
  {
    id: 37,
    name: 'Expressionism',
    section: 'Amethyst',
    mode: GameModeType.Rainbow,
    surface: 'pill',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 4_000_000, 6_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'painter', count: 10 }, { type: 'grunt', count: 15 }] },
      { delay: 28, enemies: [{ type: 'painter', count: 12 }, { type: 'grunt', count: 20 }, { type: 'weaver', count: 6 }] },
      { delay: 60, enemies: [{ type: 'painter', count: 15 }, { type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
    ],
  },
  {
    id: 38,
    name: 'Mind the Gap',
    section: 'Amethyst',
    mode: GameModeType.Evolved,
    surface: 'torus',
    surfaceScale: 11,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 5_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }] },
      { delay: 20, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }, { type: 'rocket', count: 8 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 35 }, { type: 'weaver', count: 12 }, { type: 'snake', count: 2 }] },
      { delay: 75, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 15 }, { type: 'repulsor', count: 5 }] },
    ],
  },
  {
    id: 39,
    name: 'Hexend',
    section: 'Amethyst',
    mode: GameModeType.Checkpoint,
    surface: 'sphere',
    surfaceScale: 11,
    timeLimit: 0,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [1_500_000, 3_000_000, 7_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 35 }, { type: 'rocket', count: 10 }, { type: 'weaver', count: 8 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 12 }, { type: 'neutron', count: 8 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 45 }, { type: 'weaver', count: 15 }, { type: 'snake', count: 3 }] },
    ],
  },
  {
    id: 40,
    name: 'Amethyst',
    section: 'Amethyst',
    mode: GameModeType.Boss,
    surface: 'capsule',
    surfaceScale: 13,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 4_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'boss_amethyst', count: 1 }] },
    ],
  },

  // ---- Topaz Section (41-50) ----
  {
    id: 41,
    name: 'Limit Twist',
    section: 'Topaz',
    mode: GameModeType.Sniper,
    surface: 'peanut',
    surfaceScale: 10,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [250_000, 600_000, 1_300_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 15 }, { type: 'weaver', count: 6 }] },
      { delay: 12, enemies: [{ type: 'grunt', count: 18 }, { type: 'spinner', count: 6 }] },
      { delay: 28, enemies: [{ type: 'grunt', count: 22 }, { type: 'rocket', count: 8 }, { type: 'weaver', count: 6 }] },
      { delay: 48, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 10 }, { type: 'neutron', count: 6 }] },
    ],
  },
  {
    id: 42,
    name: 'Running in the Family',
    section: 'Topaz',
    mode: GameModeType.Evolved,
    surface: 'sphere',
    surfaceScale: 13,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [2_000_000, 5_000_000, 10_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 30 }, { type: 'weaver', count: 10 }] },
      { delay: 22, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 12 }, { type: 'rocket', count: 10 }] },
      { delay: 48, enemies: [{ type: 'grunt', count: 40 }, { type: 'weaver', count: 15 }, { type: 'snake', count: 3 }] },
      { delay: 80, enemies: [{ type: 'grunt', count: 45 }, { type: 'spinner', count: 18 }, { type: 'repulsor', count: 6 }] },
      { delay: 115, enemies: [{ type: 'grunt', count: 50 }, { type: 'weaver', count: 20 }, { type: 'gravity_well', count: 3 }] },
    ],
  },
  {
    id: 43,
    name: 'Crushed',
    section: 'Topaz',
    mode: GameModeType.Deadline,
    surface: 'cube',
    surfaceScale: 12,
    timeLimit: 90,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [1_500_000, 2_500_000, 3_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 35 }, { type: 'rocket', count: 12 }, { type: 'weaver', count: 10 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 15 }, { type: 'neutron', count: 10 }] },
      { delay: 70, enemies: [{ type: 'grunt', count: 45 }, { type: 'weaver', count: 15 }, { type: 'snake', count: 3 }] },
    ],
  },
  {
    id: 44,
    name: 'Turbine Cube',
    section: 'Topaz',
    mode: GameModeType.Evolved,
    surface: 'cube',
    surfaceScale: 16,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [1_000_000, 2_000_000, 3_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }] },
      { delay: 20, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }, { type: 'rocket', count: 8 }] },
      { delay: 45, enemies: [{ type: 'grunt', count: 35 }, { type: 'weaver', count: 12 }, { type: 'repulsor', count: 5 }] },
      { delay: 75, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 15 }, { type: 'snake', count: 3 }] },
    ],
  },
  {
    id: 45,
    name: 'Deflector',
    section: 'Topaz',
    mode: GameModeType.Evolved,
    surface: 'pill',
    surfaceScale: 11,
    timeLimit: 0,
    lives: 1,
    bombs: 1,
    supers: 1,
    starThresholds: [250_000, 750_000, 1_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'repulsor', count: 6 }] },
      { delay: 18, enemies: [{ type: 'grunt', count: 25 }, { type: 'repulsor', count: 7 }, { type: 'weaver', count: 6 }] },
      { delay: 40, enemies: [{ type: 'grunt', count: 30 }, { type: 'repulsor', count: 8 }, { type: 'spinner', count: 8 }] },
      { delay: 65, enemies: [{ type: 'grunt', count: 35 }, { type: 'repulsor', count: 10 }, { type: 'snake', count: 2 }] },
    ],
  },
  {
    id: 46,
    name: 'Super Rock Crust',
    section: 'Topaz',
    mode: GameModeType.Checkpoint,
    surface: 'sphere',
    surfaceScale: 12,
    timeLimit: 0,
    lives: 0,
    bombs: 1,
    supers: 2,
    starThresholds: [400_000, 750_000, 1_500_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 25 }, { type: 'weaver', count: 8 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 30 }, { type: 'spinner', count: 10 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 35 }, { type: 'rocket', count: 10 }, { type: 'weaver', count: 8 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 12 }, { type: 'snake', count: 2 }] },
      { delay: 0, enemies: [{ type: 'grunt', count: 45 }, { type: 'weaver', count: 15 }, { type: 'repulsor', count: 6 }] },
    ],
  },
  {
    id: 47,
    name: 'Royal Disease',
    section: 'Topaz',
    mode: GameModeType.King,
    surface: 'torus',
    surfaceScale: 11,
    timeLimit: 0,
    lives: 1,
    bombs: 0,
    supers: 1,
    starThresholds: [250_000, 500_000, 1_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 20 }, { type: 'wanderer', count: 10 }] },
      { delay: 15, enemies: [{ type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
      { delay: 35, enemies: [{ type: 'grunt', count: 30 }, { type: 'weaver', count: 8 }, { type: 'rocket', count: 6 }] },
      { delay: 60, enemies: [{ type: 'grunt', count: 35 }, { type: 'spinner', count: 12 }, { type: 'repulsor', count: 4 }] },
    ],
  },
  {
    id: 48,
    name: 'Spawners Revenge',
    section: 'Topaz',
    mode: GameModeType.Deadline,
    surface: 'capsule',
    surfaceScale: 12,
    timeLimit: 120,
    lives: 0,
    bombs: 1,
    supers: 1,
    starThresholds: [5_000_000, 6_000_000, 7_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'spawner', count: 4 }, { type: 'grunt', count: 15 }] },
      { delay: 18, enemies: [{ type: 'spawner', count: 5 }, { type: 'grunt', count: 20 }, { type: 'weaver', count: 6 }] },
      { delay: 40, enemies: [{ type: 'spawner', count: 6 }, { type: 'grunt', count: 25 }, { type: 'spinner', count: 8 }] },
      { delay: 65, enemies: [{ type: 'spawner', count: 7 }, { type: 'grunt', count: 30 }, { type: 'rocket', count: 10 }] },
      { delay: 90, enemies: [{ type: 'spawner', count: 8 }, { type: 'grunt', count: 35 }, { type: 'snake', count: 3 }] },
    ],
  },
  {
    id: 49,
    name: 'Super Sequence',
    section: 'Topaz',
    mode: GameModeType.Evolved,
    surface: 'torus',
    surfaceScale: 13,
    timeLimit: 0,
    lives: 3,
    bombs: 2,
    supers: 3,
    starThresholds: [25_000_000, 50_000_000, 150_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'grunt', count: 35 }, { type: 'weaver', count: 12 }] },
      { delay: 25, enemies: [{ type: 'grunt', count: 40 }, { type: 'spinner', count: 15 }, { type: 'rocket', count: 12 }] },
      { delay: 55, enemies: [{ type: 'grunt', count: 45 }, { type: 'weaver', count: 18 }, { type: 'snake', count: 4 }] },
      { delay: 90, enemies: [{ type: 'grunt', count: 50 }, { type: 'spinner', count: 20 }, { type: 'repulsor', count: 8 }] },
      { delay: 130, enemies: [{ type: 'grunt', count: 55 }, { type: 'weaver', count: 22 }, { type: 'gravity_well', count: 4 }] },
      { delay: 175, enemies: [{ type: 'grunt', count: 60 }, { type: 'spinner', count: 25 }, { type: 'snake', count: 6 }] },
    ],
  },
  {
    id: 50,
    name: 'Topaz',
    section: 'Topaz',
    mode: GameModeType.Boss,
    surface: 'sphere',
    surfaceScale: 14,
    timeLimit: 0,
    lives: 1,
    bombs: 2,
    supers: 2,
    starThresholds: [1_000_000, 5_000_000, 15_000_000],
    waves: [
      { delay: 0, enemies: [{ type: 'boss_topaz', count: 1 }] },
    ],
  },
];
